import { useEffect, useMemo, useState } from 'react'
import { CircleMarker, MapContainer, Popup, TileLayer, useMap } from 'react-leaflet'
import type { Case, CaseStatus } from './types/cases'
import { fetchCases } from './lib/api'

const statusLabels: Record<CaseStatus,string> = { ny:'Ny', i_gang:'I gang', tilbud_sendt:'Tilbud sendt', vundet:'Vundet', tabt:'Tabt', afventer:'Afventer' }
const statusColor: Record<string,string> = { ny:'#1f9d72', i_gang:'#1769aa', tilbud_sendt:'#7c5cbf', vundet:'#0b7a4b', tabt:'#b84a4a', afventer:'#a36a16' }
function FitBounds({ cases }: { cases: Case[] }) { const map=useMap(); useEffect(()=>{const points=cases.filter(c=>c.latitude&&c.longitude).map(c=>[c.latitude!,c.longitude!] as [number,number]); if(points.length) map.fitBounds(points,{padding:[30,30],maxZoom:12})},[cases,map]); return null }
export default function App() {
  const [data,setData]=useState<Awaited<ReturnType<typeof fetchCases>>|null>(null), [error,setError]=useState(''), [selected,setSelected]=useState<Case|null>(null)
  const [search,setSearch]=useState(''), [advisor,setAdvisor]=useState(''), [department,setDepartment]=useState(''), [status,setStatus]=useState('')
  useEffect(()=>{fetchCases().then(setData).catch(e=>setError(e instanceof Error?e.message:'Uventet fejl'))},[])
  const filtered=useMemo(()=>data?.cases.filter(c=>(!search||[c.customer_name,c.address_raw,c.case_number].join(' ').toLowerCase().includes(search.toLowerCase()))&&(!advisor||c.advisor===advisor)&&(!department||c.department===department)&&(!status||c.status===status))??[],[data,search,advisor,department,status])
  const advisors=[...new Set(data?.cases.map(c=>c.advisor).filter(Boolean))] as string[], departments=[...new Set(data?.cases.map(c=>c.department).filter(Boolean))] as string[]
  if(error) return <main className="state"><h1>Der opstod en fejl</h1><p>{error}</p><p>Kontrollér backend-forbindelsen eller slå eksplicit demo mode til.</p></main>
  if(!data) return <main className="state"><div className="spinner"/><p>Henter sager…</p></main>
  return <main className="shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">N</span><div><strong>NRGi</strong><span>Salgskort</span></div></div><span className="source-pill">{data.meta.data_source==='demo'?'DEMOTILSTAND':'LIVE DATA'}</span></header>
    <section className="intro"><div><p className="eyebrow">OVERBLIK</p><h1>Sager i Danmark</h1><p className="muted">Geografisk overblik over aktive salgs- og projektsager</p></div><p className="sync">Sidst synkroniseret<br/><strong>{new Date(data.meta.fetched_at).toLocaleString('da-DK',{dateStyle:'medium',timeStyle:'short'})}</strong></p></section>
    <section className="kpis" aria-label="Nøgletal"><article><span>Alle sager</span><b>{data.meta.total_rows}</b></article><article><span>Geokodet</span><b className="green">{data.meta.resolved_count}</b></article><article><span>Ikke placeret</span><b className="orange">{data.meta.unresolved_count}</b></article><article><span>Viser nu</span><b>{filtered.length}</b></article></section>
    <section className="toolbar"><label className="search"><span aria-hidden>⌕</span><input aria-label="Søg i sager" placeholder="Søg kunde, adresse eller sagsnummer" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Rådgiver" value={advisor} onChange={e=>setAdvisor(e.target.value)}><option value="">Alle rådgivere</option>{advisors.map(a=><option key={a}>{a}</option>)}</select><select aria-label="Afdeling" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Alle afdelinger</option>{departments.map(d=><option key={d}>{d}</option>)}</select><select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Alle statusser</option>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></section>
    <section className="workspace"><div className="map-wrap"><MapContainer center={[56.2,10.1]} zoom={7} scrollWheelZoom><TileLayer attribution='&copy; OpenStreetMap contributors' url={import.meta.env.VITE_MAP_TILE_URL||'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'}/><FitBounds cases={filtered}/>{filtered.filter(c=>c.latitude&&c.longitude).map(c=><CircleMarker key={c.id} center={[c.latitude!,c.longitude!]} radius={9} pathOptions={{color:'#fff',weight:2,fillColor:statusColor[c.status||''],fillOpacity:.9}} eventHandlers={{click:()=>setSelected(c)}}><Popup><strong>{c.customer_name||'Ukendt kunde'}</strong><br/>{c.address_raw}</Popup></CircleMarker>)}</MapContainer></div><aside className="side-panel"><div className="panel-head"><h2>Sager</h2><span>{filtered.length}</span></div>{selected?<div className="detail"><button className="back" onClick={()=>setSelected(null)}>← Alle sager</button><p className="eyebrow">{selected.case_number}</p><h2>{selected.customer_name||'Ukendt kunde'}</h2><p>{selected.address_raw}</p><dl><dt>Rådgiver</dt><dd>{selected.advisor||'—'}</dd><dt>Afdeling</dt><dd>{selected.department||'—'}</dd><dt>Status</dt><dd>    <span className="status" style={{background:statusColor[selected.status||'']}}>{selected.status ? statusLabels[selected.status] : 'Ukendt'}</span></dd>{selected.estimated_value_dkk&&<><dt>Estimeret værdi</dt><dd>{selected.estimated_value_dkk.toLocaleString('da-DK')} kr.</dd></>}</dl></div>:<div className="case-list">{filtered.map(c=><button className="case-row" key={c.id} onClick={()=>setSelected(c)}><span className="dot" style={{background:statusColor[c.status||'']}}/><span><strong>{c.customer_name||'Ukendt kunde'}</strong><small>{c.address_raw}</small></span><span className="arrow">›</span></button>)}{filtered.length===0&&<p className="empty">Ingen sager matcher filtrene.</p>}</div>}{data.meta.unresolved_count>0&&<div className="unresolved"><strong>⚠ {data.meta.unresolved_count} ikke placeret</strong><p>Se fejlrapporten for adresser, der kræver manuel kontrol.</p>{data.issues.map(i=><small key={`${i.row_number}-${i.message}`}>Række {i.row_number}: {i.message}</small>)}</div>}</aside></section>
  </main>
}
